name: AutoTweetBot

on:
  schedule:
    - cron: "*/20 * * * *"   # हर 20 मिनट में run होगा
  workflow_dispatch:         # Manual run की भी सुविधा

jobs:
  tweet:
    runs-on: macos-latest

    steps:
    - name: Repo Clone
      uses: actions/checkout@v3

    - name: Python Install
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Dependencies Install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Chacha Nehru Bot
      env:
        CHATGPT_API_KEY: ${{ secrets.CHATGPT_API_KEY }}
        X_API_KEY: ${{ secrets.X_API_KEY }}
        X_API_SECRET: ${{ secrets.X_API_SECRET }}
        X_ACCESS_TOKEN: ${{ secrets.X_ACCESS_TOKEN }}
        X_ACCESS_SECRET: ${{ secrets.X_ACCESS_SECRET }}
      run: |
        python3 main.py
